// Loaded by demo apps from /config/tenant.json (generated by setup/render-tenant-config.ps1)

async function loadTenantConfig() {
  const r = await fetch("/config/tenant.json");
  if (!r.ok) throw new Error("Missing tenant.json — run setup/fresh-deploy.ps1");
  return r.json();
}

function initKeycloak(config, clientId) {
  return new Keycloak({
    url: config.keycloakUrl,
    realm: config.realm,
    clientId: clientId,
  });
}
