services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ../target/keycloak-pki-authenticator-sample.jar:/opt/keycloak/providers/keycloak-pki-authenticator-sample.jar:ro
